services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
            daphne -b 0.0.0.0 -p 8000 transcendences.asgi:application"
    volumes:
      - ./transcendences:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: transcedences
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: